### ISSUE TITLE
Download lipsync expert error

### ISSUE THREAD

**Issue by omanhom** [KU-CVLAB/Talk3D#1]
![1](https://github.com/KU-CVLAB/Talk3D/assets/13151762/6c928a41-9a53-4c89-b7df-355b3b4dedd5)

**Comment by mlnyang** [comment]
Sorry for the late response.

I hope you fixed the issue. I just tested the wget script to download the syncnetv2 model, and it worked fine.
Please let me know if you have any other issues

**Comment by omanhom** [comment]
![image](https://github.com/KU-CVLAB/Talk3D/assets/13151762/4adb189d-0291-4e07-88c9-2c5c6c3cefcd)
clicking "here" will require login and after successful login,the error above will be displayed

Finally,i downloaded from https://github.com/Rudrabha/Wav2Lip
