### ISSUE TITLE
how can I get pretrained_model?

### ISSUE THREAD

**Issue by yerang1** [KU-CVLAB/Talk3D#7]
Hi, thanks for your great works.

Can I use pretrained weights?

Or, I want to know whether you have plans to release it.

Thank you again.

**Comment by mlnyang** [comment]
Hello, thank you for your interest in our work!

In the quick start menu of 'docs/preprocessing.md', we provide pretrained weight for the May.mp4 video dataset, and we currently have no plans to release additional demos.
